const state={cases:[],filter:"all",active:null};
const $=s=>document.querySelector(s);
const badge=(text,type="neutral")=>`<span class="badge ${type}">${text}</span>`;
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function reviewLabel(status){return status==="approved"?badge("已通过","ok"):status==="needs-redaction"?badge("需脱敏","bad"):badge("待人工复核","warn")}
function renderStats(stats){const labels=[["总案例",stats.total],["文本可用",stats.usable],["仍需 OCR",stats.ocr_required],["匿名化通过",stats.approved],["含代码材料",stats.with_code],["奖项已核验",stats.award_verified]];$("#stats").innerHTML=labels.map(([k,v])=>`<article class="stat"><span>${k}</span><strong>${v}</strong></article>`).join("")}
function visible(c){if(state.filter==="all")return true;if(state.filter==="pending")return c.review.status!=="approved";if(state.filter==="approved")return c.review.status==="approved";return c.text_quality==="ocr-required"}
function renderCases(){$("#case-list").innerHTML=state.cases.filter(visible).map(c=>`<tr data-id="${c.case_id}"><td><span class="case-title">${c.year} · ${c.problem_id} 题</span><div class="sub">${c.case_id}</div></td><td><span>${c.repository_license_spdx}</span><div class="sub">${c.award_claim}</div></td><td>${c.text_quality==="usable"?badge("可用","ok"):badge("需 OCR","warn")}<div class="sub">${c.paper_pages} 页 · ${c.extraction_method}</div></td><td>${reviewLabel(c.review.status)}<div class="sub">${c.pii_findings.length} 个敏感信息候选</div></td><td>${badge(c.code_inventory.status,c.code_inventory.code_files?"ok":"neutral")}<div class="sub">${c.code_inventory.code_files} 个代码文件，未执行第三方代码</div></td><td>${c.model_upload_allowed?badge("允许","ok"):badge("禁止","bad")}</td></tr>`).join("")||`<tr><td colspan="6">当前筛选条件下没有案例。</td></tr>`;document.querySelectorAll("tbody tr[data-id]").forEach(row=>row.onclick=()=>openReview(row.dataset.id))}
async function load(){const res=await fetch("/api/corpus");if(!res.ok)throw Error("语料接口不可用");const data=await res.json();state.cases=data.cases;renderStats(data.stats);renderCases();loadQuality()}
async function loadQuality(){const res=await fetch("/api/corpus/quality");const q=await res.json();if(q.generated_at)$("#quality-summary").textContent=`上次质检：${q.summary.passed}/${q.summary.processed} 个通过流水线检查`}
function openReview(id){const c=state.cases.find(x=>x.case_id===id);state.active=c;$("#dialog-title").textContent=`${c.year} 年 ${c.problem_id} 题 · 匿名化复核`;$("#review-notes").value=c.review.notes||"";const findings=c.pii_findings.length?c.pii_findings.map(f=>`<div class="finding"><div><strong>${f.kind} · 第 ${f.line} 行</strong><br><code>${f.excerpt.replaceAll("<","&lt;")}</code></div><select data-finding="${f.id}"><option value="pending" ${f.action==="pending"?"selected":""}>待处理</option><option value="redact" ${f.action==="redact"?"selected":""}>确认删除</option><option value="false-positive" ${f.action==="false-positive"?"selected":""}>标记误报并恢复</option></select></div>`).join(""):'<p>自动扫描未发现手机号、邮箱、身份证号、队号或身份字段。仍需人工抽查论文首页、致谢和附录。</p>';$("#dialog-content").innerHTML=`<section class="dialog-section"><div class="detail-grid"><div class="detail-card"><span>文本质量</span><strong>${c.text_quality}</strong></div><div class="detail-card"><span>奖项证据</span><strong>${c.award_evidence_status}</strong></div><div class="detail-card"><span>模型门禁</span><strong>${c.model_upload_allowed?"允许":"禁止"}</strong></div></div></section><section class="dialog-section"><h3>敏感信息候选</h3>${findings}</section><section class="dialog-section"><h3>代码复现材料</h3><p>${c.code_inventory.code_files} 个代码文件；${c.code_inventory.data_files} 个数据文件；随机种子线索 ${c.code_inventory.random_seed_mentions} 处。</p><p class="sub">出于安全原因，下载的第三方代码只做静态清单检查，未在主机上执行。</p></section>`;$("#review-dialog").showModal()}
async function saveReview(status){const actions={};document.querySelectorAll("[data-finding]").forEach(x=>actions[x.dataset.finding]=x.value);const res=await fetch(`/api/corpus/${state.active.case_id}/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,notes:$("#review-notes").value,actions})});const body=await res.json();if(!res.ok){toast(body.error||"保存失败");return}state.cases=state.cases.map(x=>x.case_id===body.case_id?body:x);$("#review-dialog").close();renderCases();toast(status==="approved"?"匿名化复核已通过":"复核进度已保存")}
$("#filters").onclick=e=>{const button=e.target.closest("button");if(!button)return;document.querySelectorAll("#filters button").forEach(x=>x.classList.toggle("active",x===button));state.filter=button.dataset.filter;renderCases()};
$("#save-review").onclick=()=>saveReview("needs-redaction");$("#approve-review").onclick=()=>saveReview("approved");$("#run-quality").onclick=async()=>{const b=$("#run-quality");b.disabled=true;b.textContent="质检运行中…";try{const res=await fetch("/api/corpus/quality",{method:"POST"});const q=await res.json();if(!res.ok)throw Error(q.error||"运行失败");$("#quality-summary").textContent=`本次质检：${q.summary.passed}/${q.summary.processed} 个通过流水线检查`;toast("批量质检完成，不含教师一致率指标")}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent="运行未标注批量质检"}};
load().catch(e=>toast(e.message));
